name: Run Python tests

on:
  push:
    branches: [ main ]  # - add for limiting it only to pushes on a main branch
    paths:  # triggers testing action if only any python / 2 other files have been changed
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/test.yaml'
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code  # loads code from a repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run tests
        run: pytest
